### ISSUE TITLE
nil slice append도 가능합니다.

### ISSUE THREAD

**Issue by zrma** [jjori-master/1d1Go#1]
https://github.com/jjori-master/1d1Go/blob/b52208ebf645589ffa8d057364d15e327412d7cf/src/hello/unit22_slice.go#L27

@jjori-master 

```go
var arr []int
arr = append(arr, []int{1,2,3}...)
```

테스트 한 번 해 보시고 이 이슈는 닫아주세요 :)

**Comment by jjori-master** [comment]
@zrma 

아 뭘 잘못했는지. 패키지랑 다 깨지네요.. 에공

**Comment by zrma** [comment]
@jjori-master 

go module 셋팅부터 하시죠.

**Comment by jjori-master** [comment]
@zrma 

잘 되네요~~

끗!!~
